# Generated by Django 4.2.11 on 2024-04-21 21:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_post_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(blank=True, default=''),
        ),
    ]
